import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, FileHeart, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { formatTreatmentAreaKey } from "@shared/dentalAreas";

export default function PatientHistory() {
  const { isAuthenticated } = useAuth(); const [, params] = useRoute("/patients/:id"); const patientId = Number(params?.id || 0); const history = trpc.consent.patientHistory.useQuery({ patientId }, { enabled: isAuthenticated && Boolean(patientId), retry: false });
  if (!isAuthenticated) return <main className="workspace-page"><div className="clinical-panel p-8"><h1 className="serif text-4xl text-[#24453e]">Sign in to view patient history.</h1></div></main>;
  if (history.isLoading) return <main className="workspace-page"><div className="h-80 animate-pulse rounded-[1.35rem] bg-white" /></main>;
  if (history.error || !history.data) return <main className="workspace-page"><div className="clinical-panel max-w-2xl p-8"><h1 className="serif text-4xl text-[#24453e]">Patient history unavailable</h1><p className="mt-3 text-sm text-muted-foreground">Confirm clinic access and try again.</p></div></main>;
  const acknowledgementCounts = new Map<number, number>(); history.data.acknowledgements.forEach(item => acknowledgementCounts.set(item.consentRecordId, (acknowledgementCounts.get(item.consentRecordId) || 0) + 1));
  return <main className="workspace-page"><Link href="/records" className="inline-flex items-center text-sm font-semibold text-[#2f6656]"><ArrowLeft className="mr-2 size-4" />Consent register</Link><header className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="metric-label">Encrypted patient identity</p><h1 className="serif mt-1 text-4xl text-[#24453e]">{history.data.patient.displayName}</h1><p className="mt-2 text-sm text-muted-foreground">Patient record #{history.data.patient.id} · clinic-scoped consent history</p></div><div className="rounded-xl bg-[#edf1ea] px-4 py-3 text-sm font-semibold text-[#2f6656]"><ShieldCheck className="mr-2 inline size-4" />{history.data.consents.length} linked consent record{history.data.consents.length === 1 ? "" : "s"}</div></header><section className="clinical-panel mt-7 overflow-hidden"><div className="border-b border-[#eee9df] px-6 py-5"><p className="font-semibold text-[#24453e]">Consent history</p><p className="mt-1 text-xs text-muted-foreground">Prior procedures, withdrawals, and acknowledged disclosures remain linked to this encrypted patient entity.</p></div><div className="divide-y divide-[#eee9df]">{history.data.consents.map(({ record, product, source }) => <div key={record.id} className="flex flex-col gap-4 px-6 py-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold text-[#24453e]">{record.procedureName}</p><p className="mt-1 text-xs text-muted-foreground">{product ? product.name : "Procedure-only consent"} · {formatTreatmentAreaKey(record.treatmentAreaKey)} · {new Date(record.createdAt).toLocaleDateString()}</p><p className="mt-1 text-xs text-muted-foreground">{source ? source.documentTitle : "No product document"} · {acknowledgementCounts.get(record.id) || 0} recorded acknowledgement{(acknowledgementCounts.get(record.id) || 0) === 1 ? "" : "s"}{record.withdrawalReason ? ` · Withdrawal: ${record.withdrawalReason}` : ""}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] ${record.status === "voided" ? "bg-[#fff0ea] text-[#8a4335]" : record.status === "signed" ? "bg-[#edf1ea] text-[#2f6656]" : "bg-[#f7efe0] text-[#8a6b34]"}`}>{record.status}</span><Link href={`/review/${record.id}`}><Button size="sm" variant="outline">Open</Button></Link></div></div>)}</div>{!history.data.consents.length && <div className="p-10 text-center"><FileHeart className="mx-auto size-8 text-[#2f6656]" /><p className="mt-3 font-semibold text-[#24453e]">No linked consent records</p></div>}</section></main>;
}
