import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { buildTreatmentMapConsentContext } from "@shared/treatmentMapContext";
import { TreatmentMapContextCards } from "../components/TreatmentMapContextCards";
import { ArrowLeft, CircleDotDashed, MapPin, Trash2 } from "lucide-react";
import { MouseEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation, useRoute } from "wouter";

const areas = ["glabella", "forehead", "crow-feet", "temples", "cheeks", "nasolabial-folds", "lips", "chin", "jawline", "nose", "other"];

export default function TreatmentMap() {
  const { isAuthenticated } = useAuth();
  const [, params] = useRoute("/treatment-map/:id");
  const [, navigate] = useLocation();
  const recordId = Number(params?.id || 0);
  const utils = trpc.useUtils();
  const detail = trpc.consent.get.useQuery({ recordId }, { enabled: isAuthenticated && Boolean(recordId), retry: false });
  const entries = trpc.consent.mapEntries.useQuery({ recordId }, { enabled: isAuthenticated && Boolean(recordId), retry: false });
  const [point, setPoint] = useState<{ x: number; y: number } | null>(null);
  const [area, setArea] = useState("glabella"); const [measureType, setMeasureType] = useState<"units" | "ml" | "other">("units"); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const [view, setView] = useState<"front" | "left" | "right">("front");
  const add = trpc.consent.addMapEntry.useMutation({ onSuccess: () => { toast.success("Treatment point saved"); setPoint(null); setAmount(""); setNote(""); utils.consent.mapEntries.invalidate({ recordId }); utils.consent.get.invalidate({ recordId }); }, onError: error => toast.error(error.message) });
  const remove = trpc.consent.deleteMapEntry.useMutation({ onSuccess: () => { toast.success("Treatment point removed"); utils.consent.mapEntries.invalidate({ recordId }); }, onError: error => toast.error(error.message) });
  const visibleEntries = useMemo(() => entries.data?.filter(entry => entry.faceView === view) || [], [entries.data, view]);
  const choosePoint = (event: MouseEvent<SVGSVGElement>) => { const rect = event.currentTarget.getBoundingClientRect(); setPoint({ x: Number(((event.clientX - rect.left) / rect.width).toFixed(4)), y: Number(((event.clientY - rect.top) / rect.height).toFixed(4)) }); };
  if (!isAuthenticated) return <main className="workspace-page"><div className="clinical-panel p-8"><h1 className="serif text-4xl text-[#24453e]">Sign in to document treatment mapping.</h1></div></main>;
  if (detail.isLoading) return <main className="workspace-page"><div className="h-96 animate-pulse rounded-[1.35rem] bg-white" /></main>;
  if (detail.error || !detail.data) return <main className="workspace-page"><div className="clinical-panel p-8"><h1 className="serif text-4xl text-[#24453e]">Treatment map unavailable</h1><p className="mt-2 text-sm text-muted-foreground">Open a consent draft from the clinic workspace to document treatment points.</p></div></main>;
  const { record, product } = detail.data;
  const mapContext = buildTreatmentMapConsentContext(record, product, detail.data.practitioner);
  const isDraft = record.status === "draft";
  return <main className="workspace-page"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><button onClick={() => navigate(`/review/${recordId}`)} className="inline-flex items-center gap-1 text-xs font-semibold text-[#2f6656]"><ArrowLeft className="size-3.5" />Consent review</button><p className="metric-label mt-4">Clinical documentation</p><h1 className="serif mt-1 text-4xl font-semibold text-[#24453e]">Facial treatment map</h1><p className="mt-2 text-sm text-muted-foreground">Document treatment locations and quantities for <strong className="font-semibold text-[#24453e]">{product.name}</strong>. This map records clinical documentation; it does not prescribe technique.</p></div><Link href={`/review/${recordId}`} className="rounded-xl bg-[#24453e] px-4 py-3 text-sm font-semibold text-white">Return to consent</Link></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_0.78fr]"><section className="clinical-panel p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-[#24453e]">Select a location</h2><p className="mt-1 text-xs text-muted-foreground">Click the diagram to add a draft treatment point.</p></div><div className="flex rounded-xl bg-[#f0ede6] p-1">{(["front", "left", "right"] as const).map(faceView => <button key={faceView} onClick={() => { setView(faceView); setPoint(null); }} className={`rounded-lg px-3 py-2 text-xs font-semibold capitalize ${view === faceView ? "bg-white text-[#24453e] shadow-sm" : "text-[#77776f]"}`}>{faceView}</button>)}</div></div>
        <div className="relative mx-auto mt-5 max-w-[380px] overflow-hidden rounded-[2rem] border border-[#e5dfd5] bg-[#faf9f6]"><svg viewBox="0 0 380 520" onClick={choosePoint} className="block w-full cursor-crosshair touch-none" aria-label="Click to document a facial treatment location"><rect width="380" height="520" fill="#faf9f6" /><path d="M190 48 C128 48 99 96 102 181 C103 253 126 330 151 388 C165 421 166 447 157 470 L223 470 C214 447 215 421 229 388 C254 330 277 253 278 181 C281 96 252 48 190 48Z" fill="#f4e4d5" stroke="#bca99b" strokeWidth="2"/><path d="M129 188 C151 174 168 174 181 187" fill="none" stroke="#6d5d55" strokeWidth="3" strokeLinecap="round"/><path d="M199 187 C212 174 229 174 251 188" fill="none" stroke="#6d5d55" strokeWidth="3" strokeLinecap="round"/><path d="M190 190 L176 270 L193 276" fill="none" stroke="#af9688" strokeWidth="2" strokeLinecap="round"/><path d="M155 328 C176 342 204 342 225 328" fill="none" stroke="#9a7466" strokeWidth="3" strokeLinecap="round"/><ellipse cx="142" cy="269" rx="31" ry="22" fill="#edcfc1" opacity=".5"/><ellipse cx="238" cy="269" rx="31" ry="22" fill="#edcfc1" opacity=".5"/>{visibleEntries.map((entry, index) => <g key={entry.id} transform={`translate(${Number(entry.coordinateX) * 380}, ${Number(entry.coordinateY) * 520})`}><circle r="12" fill="#28594e" stroke="white" strokeWidth="3"/><text y="4" textAnchor="middle" fill="white" fontSize="10" fontWeight="700">{index + 1}</text></g>)}{point && <g transform={`translate(${point.x * 380}, ${point.y * 520})`}><circle r="13" fill="#c18c4c" stroke="white" strokeWidth="3"/><circle r="4" fill="white"/></g>}</svg><p className="absolute bottom-3 left-0 right-0 text-center text-[10px] font-semibold uppercase tracking-[0.12em] text-[#8a897f]">Documentation diagram</p></div>
        <TreatmentMapContextCards context={mapContext} pointCount={entries.data?.length || 0} />
      </section><aside className="clinical-panel p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#e9e1d3] text-[#24453e]"><MapPin className="size-5" /></div><div><h2 className="font-semibold text-[#24453e]">{point ? "Document selected point" : "Treatment point details"}</h2><p className="text-xs text-muted-foreground">{point ? `Map position ${(point.x * 100).toFixed(0)}%, ${(point.y * 100).toFixed(0)}%` : "Select a point on the diagram to begin."}</p></div></div>{isDraft ? <><div className="mt-6 space-y-4"><div className="space-y-2"><Label>Anatomical area</Label><select value={area} onChange={e => setArea(e.target.value)} className="h-10 w-full rounded-xl border border-[#ded7cb] bg-white px-3 text-sm">{areas.map(item => <option key={item} value={item}>{item.replaceAll("-", " ")}</option>)}</select></div><div className="grid grid-cols-[1fr_0.8fr] gap-3"><div className="space-y-2"><Label>Quantity</Label><Input type="number" min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0" className="h-10 rounded-xl" /></div><div className="space-y-2"><Label>Measure</Label><select value={measureType} onChange={e => setMeasureType(e.target.value as typeof measureType)} className="h-10 w-full rounded-xl border border-[#ded7cb] bg-white px-3 text-sm"><option value="units">Units</option><option value="ml">mL</option><option value="other">Other</option></select></div></div><div className="space-y-2"><Label>Clinical note</Label><Textarea value={note} onChange={e => setNote(e.target.value)} placeholder="Optional documented note" className="min-h-24 rounded-xl" /></div></div><Button disabled={!point || !amount || add.isPending} onClick={() => point && add.mutate({ recordId, productId: record.productId, faceView: view, areaKey: area, coordinateX: point.x, coordinateY: point.y, measureType, amount: Number(amount), clinicalNote: note || undefined })} className="mt-5 w-full bg-[#24453e] text-white"><CircleDotDashed className="mr-2 size-4" />Save treatment point</Button></> : <div className="mt-6 rounded-2xl border border-[#d8c9ad] bg-[#fff8e9] p-4 text-sm leading-relaxed text-[#675b42]">This consent has left draft status. Its mapped points are retained in the treatment record and cannot be edited here.</div>}
        <div className="mt-7 border-t border-[#eee9df] pt-5"><p className="text-sm font-semibold text-[#24453e]">Documented points</p><div className="mt-3 space-y-2">{entries.data?.length ? entries.data.map((entry, index) => <div key={entry.id} className="flex items-center justify-between rounded-xl bg-[#f7f5f0] px-3 py-3"><div><p className="text-xs font-semibold capitalize text-[#24453e]">{index + 1}. {entry.areaKey.replaceAll("-", " ")}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{entry.amount} {entry.measureType} · {entry.faceView}</p></div>{isDraft && <button onClick={() => remove.mutate({ entryId: entry.id })} className="grid size-8 place-items-center rounded-lg text-[#a85145] hover:bg-white" aria-label="Remove treatment point"><Trash2 className="size-4" /></button>}</div>) : <p className="text-xs text-muted-foreground">No treatment points documented yet.</p>}</div></div>
      </aside></div></main>;
}
