import React from "react";
import type { AuditFilterState } from "@shared/auditFilters";

export type AuditRecordOption = { id: number; label: string };
export function mergeAuditFilterState(current: AuditFilterState, patch: Partial<AuditFilterState>) { return { ...current, ...patch }; }

export function AuditFilterControls({ value, onChange, records }: { value: AuditFilterState; onChange: (next: AuditFilterState) => void; records: AuditRecordOption[] }) {
  const update = (patch: Partial<AuditFilterState>) => onChange(mergeAuditFilterState(value, patch));
  return <div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><select value={value.recordId} onChange={e => update({ recordId: e.target.value })} className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs"><option value="">All consent records</option>{records.map(record => <option key={record.id} value={record.id}>{record.label}</option>)}</select><input value={value.actor} onChange={e => update({ actor: e.target.value })} placeholder="Actor" className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs" /><input value={value.patient} onChange={e => update({ patient: e.target.value })} placeholder="Patient surname" className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs" /><input value={value.procedure} onChange={e => update({ procedure: e.target.value })} placeholder="Procedure" className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs" /><input value={value.product} onChange={e => update({ product: e.target.value })} placeholder="Product" className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs" /><input value={value.practitioner} onChange={e => update({ practitioner: e.target.value })} placeholder="Practitioner" className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs" /><select value={value.status} onChange={e => update({ status: e.target.value as AuditFilterState["status"] })} className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs"><option value="">All signature statuses</option><option value="draft">Draft</option><option value="sent">Sent</option><option value="paper_prepared">Paper package prepared</option><option value="signed">Electronically signed</option><option value="paper_signed">Paper signature recorded</option><option value="voided">Voided</option></select><input value={value.dateFrom} onChange={e => update({ dateFrom: e.target.value })} type="date" aria-label="Audit date from" className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs" /><input value={value.dateTo} onChange={e => update({ dateTo: e.target.value })} type="date" aria-label="Audit date to" className="h-9 rounded-lg border border-[#ded7cb] bg-white px-3 text-xs" /></div>;
}
